# Generated by Django 4.0.3 on 2022-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('is_premium', models.BooleanField(null=True)),
                ('promotion_end_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
